# Generated by Django 6.1 on 2026-09-11 00:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LicenciaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico', models.CharField(max_length=120)),
                ('rut_medico', models.CharField(max_length=12)),
                ('funcionario', models.CharField(max_length=120)),
                ('rut_funcionario', models.CharField(max_length=12)),
                ('dias_reposo', models.IntegerField()),
                ('fecha_emision', models.DateField()),
                ('tipo_licencia', models.PositiveSmallIntegerField(choices=[(1, 'Enfermedad o accidente comun'), (2, 'Medicina preventiva'), (3, 'Licencia pre y postnatal'), (4, 'Enfermedad grave del nino menor de un anio'), (5, 'Accidente del trabajo o del trayecto'), (6, 'Enfermedad profesional'), (7, 'Patologias del embarazo')])),
                ('estado', models.CharField(choices=[('Aceptada', 'Aceptada'), ('Rechazo - fecha invalida', 'Rechazo - fecha invalida'), ('Rechazo - dias excedidos', 'Rechazo - dias excedidos'), ('Dato invalido', 'Dato invalido')], max_length=40)),
                ('motivo', models.TextField()),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('eliminado', models.BooleanField(default=False)),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-fecha',),
            },
        ),
    ]
