# Generated by Django 6.1 on 2026-09-16 19:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenciamedica',
            name='estado',
            field=models.CharField(choices=[('Aceptada', 'Aceptada'), ('Rechazo - fecha invalida', 'Rechazo - fecha invalida'), ('Rechazo - dias excedidos', 'Rechazo - dias excedidos'), ('Rechazo - medico sancionado', 'Rechazo - medico sancionado'), ('Dato invalido', 'Dato invalido')], max_length=40),
        ),
        migrations.CreateModel(
            name='MedicoSancionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_medico', models.CharField(max_length=20)),
                ('nombre_medico', models.CharField(max_length=240)),
                ('numero_oficio', models.CharField(blank=True, max_length=80)),
                ('fecha_oficio', models.DateField(blank=True, null=True)),
                ('monto_multa_utm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('suspension_dias', models.PositiveIntegerField(blank=True, null=True)),
                ('inicio_suspension', models.DateField(blank=True, null=True)),
                ('fin_suspension', models.DateField(blank=True, null=True)),
                ('fuente_url', models.URLField(max_length=500)),
                ('fecha_carga', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('datos_origen', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ('-inicio_suspension', 'nombre_medico'),
                'constraints': [models.UniqueConstraint(fields=('rut_medico', 'numero_oficio', 'inicio_suspension', 'fin_suspension'), name='unique_sancion_medico_periodo')],
            },
        ),
    ]
